# More information about the pubspec format in <https://dart.dev/tools/pub/pubspec>.
name: gs_manager
description: Aplicativo utilizado para gerenciar a empresa "Gislaine Studio" em Andradina-SP, Brasil.
homepage: https://gislainestudio.com.br
repository: https://github.com/NatanAmorim/gs_manager
version: 24.03.10-beta
# Prevent accidental publishing to pub.dev.
publish_to: "none"
# TODO add `false_secrets` more info in <https://dart.dev/tools/pub/pubspec#false_secrets>

# This app supports only Android.
platforms:
  android:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  # This is overkill, and requires a specific version of the `http` package. I
  # just wanted to play an audio file. But I don't want to learn how to do "Dart
  # interoperability with Android" just to play the audio, and the app is only
  # used by 1 or 2 managers, I don't need to optimize and can use a bloated pkg.
  audioplayers: ^5.2.1
  flutter_animate: ^4.2.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  grpc: ^3.2.4
  http: ^1.1.0
  intl: ^0.18.1
  local_auth: ^2.1.6
  logging: ^1.2.0
  package_info_plus: ^5.0.1
  protobuf: ^3.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.6.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.10
  freezed: ^2.3.2
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sounds/material_product_sounds/
    - pubspec.yaml

# This package generates native code to customize Flutter's default white native splash screen
# with background color and splash image.
# To apply changes run the following command in the terminal:
# `dart run flutter_native_splash:create`
# To restore Flutter's default white splash screen, run the following command in the terminal:
# `dart run flutter_native_splash:remove`
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#F7DFEF"
  color_dark: "#322633"
  image: assets/images/gislaine_studio_logo.png
  image_dark: assets/images/gislaine_studio_logo.png
  android_12:
    image: assets/images/gislaine_studio_logo.png
    icon_background_color: "#F7DFEF"
    image_dark: assets/images/gislaine_studio_logo.png
    icon_background_color_dark: "#322633"

# A tool that simplifies the task of updating your Flutter APP launcher icon.
# Run the package
# After setting up the configuration, all that is left to do is run the package.
# `dart run flutter_launcher_icons`
flutter_launcher_icons:
  adaptive_icon_background: "#322633"
  adaptive_icon_foreground: "assets/images/gs_manager_logo.png"
  image_path: "assets/images/gs_manager_logo.png"
  android: true
  min_sdk_android: 21
  ios: false
  # remove_alpha_ios: true
  # background_color_ios: "#322633"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
