name: gs_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animations: ^2.0.7
  audioplayers: ^4.1.0
  dio: ^5.3.0
  flutter_animate: ^4.2.0
  flutter_riverpod: ^2.3.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  intl: ^0.18.0
  local_auth: ^2.1.6
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.0.2
  shared_preferences: ^2.0.15
  # https://pub.dev/packages/jiffy

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.4
  freezed: ^2.3.2
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sounds/material_product_sounds/

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#000000"
  image: assets/images/gs_manager_logo.png
  android_12:
    image: assets/images/gs_manager_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/gs_manager_logo.png
    icon_background_color_dark: "#000000"

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/gs_manager_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
